### PR TITLE
Segmentation fault on WSL

### PR DESCRIPTION
**Pull request by sbarzaghialteaup**
All the commands on WSL do the jobs correctly but then they get terminated with segmentation fault.
Doing a hana client disconnect() solved the problem, if it is ok I can change all the commands

```
> hana-cli serviceKey
Input: CF/XS Service Instance Name:  test-hanatrial-db
Input: CF/XS Service Key Name:  hana-cli
Service Key hana-cli created
Getting key hana-cli for service instance test-hanatrial-db as sbarzaghi@alteanet.it...
Current User                                                   Current Schema
-------------------------------------------------------------  --------------------------------
E56F46F086A64647BBE8C42804FF5AC2_0ERYBTS8G58PZMBDPDQUN11M5_RT  E56F46F086A64647BBE8C42804FF5AC2

HOST                                  PORT   CONNECTION_ID  KEY                 VALUE                                                          SECTION
------------------------------------  -----  -------------  ------------------  -------------------------------------------------------------  -------
0b0f5d1a-e092-4151-ac37-6e03c3ffffff  30040  202141         APPLICATION         node                                                           SYSTEM
0b0f5d1a-e092-4151-ac37-6e03c3ffffff  30040  202141         APPLICATIONUSER     sbarzaghi                                                      SYSTEM
0b0f5d1a-e092-4151-ac37-6e03c3ffffff  30040  202141         XS_APPLICATIONUSER  E56F46F086A64647BBE8C42804FF5AC2_0ERYBTS8G58PZMBDPDQUN11M5_RT  SYSTEM
0b0f5d1a-e092-4151-ac37-6e03c3ffffff  30040  202141         PROTOCOL_VERSION    4.1 (6, 8)                                                     SYSTEM
0b0f5d1a-e092-4151-ac37-6e03c3ffffff  30040  202141         DRIVERVERSION       2.8.20                                                         USER

The default-env.json file was saved with connection details!
Segmentation fault
```

### CODE REVIEW

**Comment by jung-thomas** [comment]
I tested on WSL - Ubuntu and I don't receive any Segmentation fault messages. What Linux flavor are you using?  And when you run hana-cli version what version of @sap/hana-client are you seeing?

**Comment by sbarzaghialteaup** [comment]
@sap/hana-client version is 2.8.20

These are the results after some tests, the problem seems related only to the node version.

Tried on:
WSL Ubuntu 18.04.4 LTS
WSL Ubuntu 20.04.1 LTS
WSL Ubuntu VM

Node version:
12.18.3 segmentation fault (my current release on all the systems)
12.22.1 segmentation fault (latest 12.x release)
14.16.1 segmentation fault (latest 14.16.x release)
14.17.0 no error (is the first 14.17.x release and latest 14.x release)
16.2.0 no error (latest 16.x release, hana-cli warning for unsupported engine during installation)

On Windows there is no segmentation fault but with node < 14.17.0 the %errorcode% is not zero:

```
nvm-noinstall>node -v
v12.22.1

nvm-noinstall>hana-cli status
Using Connection Configuration loaded via default-env.json

Current User                                                   Current Schema
-------------------------------------------------------------  --------------------------------
E56F46F086A64647BBE8C42804FF5AC2_0ERYBTS8G58PZMBDPDQUN11M5_RT  E56F46F086A64647BBE8C42804FF5AC2
...

nvm-noinstall>echo %errorlevel%
-1073740940
```

Starting from 14.17.0
```
nvm-noinstall>node -v
v16.2.0

nvm-noinstall>hana-cli status
Using Connection Configuration loaded via default-env.json

Current User                                                   Current Schema
-------------------------------------------------------------  --------------------------------
E56F46F086A64647BBE8C42804FF5AC2_0ERYBTS8G58PZMBDPDQUN11M5_RT  E56F46F086A64647BBE8C42804FF5AC2
...

nvm-noinstall>echo %errorlevel%
0
```

**Comment by jung-thomas** [comment]
I'm going to close this pull request without merging.  Not that there is anything wrong with it. I did decide to go ahead and add the hana client close. However rather than add that to every command, I did a little restructuring so that that new logic is only in the /utils/base library. 
https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/hana_client_restructure/utils/base.js#L249

You can try it out if you want from this other branch:
https://github.com/SAP-samples/hana-developer-cli-tool-example/tree/hana_client_restructure

I'm mostly done with the changes. I've tested it completely on HANA Cloud but need to finish some testing tomorrow on HANA 2.0+XSA.

**Comment by ThePlenkov** [comment]
@sbarzaghialteaup you are genious! I spent so much time on finding this. But went to a wrong direction - I thought is file access issue

**Comment by sbarzaghialteaup** [comment]
> @sbarzaghialteaup you are genious! I spent so much time on finding this. But went to a wrong direction - I thought is file access issue

genious? exaggerated ;-)

**Pull request closed without merging**
